name: Static code analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up
        run: docker-compose up -d --build
      - name: Build project and update DB scheme
        run: docker exec trigger_web ./.docker/develop_init.sh
      - name: Run PHPSTAN
        run: docker exec trigger_web ./vendor/bin/phpstan analyse src --level 5
